version: '3.3'

services:
  ocdb:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oc
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  oc:
    image: webdevops/php-apache:7.3
    depends_on:
      - ocdb
    restart: always
#     build:
#       context: ./docker
#       dockerfile: stopo.dockerfile
    working_dir: /var/www/html
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/web
      WEB_ALIAS_DOMAIN: oc.local.dev
      VIRTUAL_HOST: oc.local.dev
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: HTTP
    volumes:
      - ./custom_modules:/var/www/html/web/modules/custom
      - ./theme:/var/www/html/web/themes/custom/oc
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./config:/var/www/html/config
      - ./settings/settings.php:/var/www/html/web/sites/default/settings.php
      - ./settings/settings.local.php:/var/www/html/web/sites/default/settings.local.php
      - ./settings/development.services.yml:/var/www/html/web/sites/default/development.services.yml
      - ./settings/load.environment.php:/var/www/html/load.environment.php
      - ./scripts:/var/www/html/scripts
      - ./files:/var/www/html/web/sites/default/files
      - ./backups:/var/www/html/backups
      - ./community_integration:/var/www/html/web/community_integration
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
     - ocdb:db
    ports:
    - 8009:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: ocdb
      
networks:
  default:
    external:
      name: proxy
