/**                                                                                                                                                                                                                                                                      
* Require Browsersync                                                                                                                                                                                                                                                   
*/                                                                                                                                                                                                                                                                     
var browserSync = require('browser-sync').create();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
/**                                                                                                                                                                                                                                                                      
* Run Browsersync with server config                                                                                                                                                                                                                                    
* You can use an arrays for files to specify multiple files                                                                                                                                                                                                             
*/                                                                                                                                                                                                                                                                     
browserSync.init({                                                                                                                                                                                                                                                          
  proxy: "https://ihgownersassociation.force.com/connect/s/",                                                                                                                                                                                                                               
  serveStatic: ['dist'],                                                                                                                                                                                                                                                  
  files: ["dist/css/*.css", "dist/js/*.js", "dist/images/*"],                                                                                                                                                                                                             
  rewriteRules: [                                                                                                                                                                                                                                                             
  {                                                                                                                                                                                                                                                                         
    match: '//connect.owners.org/dist/css/community.css',
    replace: '/dist/css/community.css'
  },                                                                                                                                                                                                                                                                      
  {                                                                                                                                                                                                                                                                         
    match: 'https://new.merlinautogroup.com/scripts/index.min.js',                                                                                                                                                                                                          
    replace: '/scripts/index.min.js'                                                                                                                                                                                                                                      
  }                                                                                                                                                                                                                                                                   
]                                                                                                                                                                                                                                                                   
});                                                                                                                                                                                                                                                                             
